apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ugxq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ugxq
    app.kubernetes.io/part-of: tkrw-pr712-0075-0037-app
  name: devfile-sample-ugxq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ugxq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ugxq
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0037-tenant/tkrw-pr712-0075-0037-app/devfile-sample-ugxq@sha256:75dfc12206cb03783e665d2095015d505fa7e1d6c658e341a60b797768b8d8c9
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
